### ISSUE TITLE
Epic : LeaderBoard

### ISSUE THREAD

**Issue by imfeldd** [CPNV-ES/run4cause-qx#3]
# Description

Le but de cette epic est de réaliser une page de LeaderBoard affichant l'avancement de chaque participant.

# Issues
- [ ] LeaderBoard: Carte de la course
- [ ] LeaderBoard: Icônes des participants 

# Definition of Done
- [ ] La page de leaderboard répond aux exigences de fonctionnalité de cette epic
