### ISSUE TITLE
Epic : Gestion des roles

### ISSUE THREAD

**Issue by SuperQuentin** [CPNV-ES/run4cause-qx#7]
## Description

Mise en place d'un système de gestion de rôles à l'aide d'une Access Control List pour pouvoir gérer avec granularité les permissions.

## Issues

- [ ] Création d'un mld permettant la gestion des permissions
- [ ] Création des migrations pour générer des utilisateurs
- [ ] Création des migrations pour générer les rôles et les permissions
- [ ] Création d'une interface permettant le CRUD des rôles

## Definition of done
- [ ] Lors de la création d'un nouvel utilisateur il possède un rôle par défaut
- [ ] L'administrateur peut ajouter un nouveau rôle et définir ces permissions
- [ ] L'interface est accessible depuis un poste fixe ou un dispositif mobile
